#!/bin/sh
### BEGIN INIT INFO
# Provides:          pinset
# Required-Start:    $local_fs $remote_fs $network $syslog $named $lightdm
# Required-Stop:     $local_fs $remote_fs $network $syslog $named $lightdm
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop piset
### END INIT INFO

INSTALLDIR=/root/sbs

export PYTHONPATH=$PYTHONPATH:$INSTALLDIR/modules
$INSTALLDIR/daemon/pinset.py &
$INSTALLDIR/daemon/taskmon.py &
exit 0
